# Generated by Django 3.0.4 on 2020-03-18 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_last_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='github_user',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
