# Generated by Django 3.0.4 on 2020-03-18 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200317_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_modified',
            field=models.DateTimeField(),
        ),
    ]
