# Generated by Django 3.0.4 on 2020-03-18 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200318_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
